version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.10
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: flask-migrate
    versions:
    - 2.6.0
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: flask-sqlalchemy
    versions:
    - 2.4.4
  - dependency-name: jinja2
    versions:
    - 2.10.1
